services:
  - type: web
    name: moonstore
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: "127.0.0.1"
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: "lv_moonstore"
      - key: DB_USERNAME
        value: "root"
      # DB_PASSWORD is completely removed (empty password)
