services:
  - type: web
    name: moonstore
    env: php
    buildCommand: "composer install --no-dev && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: "127.0.0.1"
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: "lv_moonstore"
      - key: DB_USERNAME
        value: "root"
      - key: DB_PASSWORD
        value: ""     # ← replace with your phpMyAdmin password
